import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const imageDir = path.join(root, "public/assets/img");
const docsDir = path.join(root, "docs");
const outputPath = path.join(docsDir, "image-inventory.md");
const derivativeTargets = [
  { label: "Photography", dir: path.join(imageDir, "thumbs", "photography"), expected: 21 },
  { label: "Mission Log", dir: path.join(imageDir, "thumbs", "mission-log"), expected: 55 }
];

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(fullPath) : [fullPath];
  });
}

function formatBytes(bytes) {
  if (bytes >= 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
  return `${Math.round(bytes / 1024)} KB`;
}

for (const target of derivativeTargets) {
  const count = fs.existsSync(target.dir)
    ? walk(target.dir).filter((file) => file.endsWith(".webp")).length
    : 0;
  if (count !== target.expected) {
    throw new Error(`${target.label}: expected ${target.expected} WebP thumbnails, found ${count}`);
  }
}

const imageFiles = walk(imageDir)
  .filter((file) => /\.(png|jpe?g|webp|svg|ico)$/i.test(file))
  .map((file) => {
    const rel = path.relative(path.join(root, "public"), file).replace(/\\/g, "/");
    const bytes = fs.statSync(file).size;
    return { rel, bytes };
  })
  .sort((a, b) => b.bytes - a.bytes);

const largeImages = imageFiles.filter((image) => image.bytes >= 1024 * 1024);
const totalBytes = imageFiles.reduce((sum, image) => sum + image.bytes, 0);

const lines = [
  "# Image Inventory",
  "",
  "Generated by `npm run audit:images`.",
  "",
  `Total images: ${imageFiles.length}`,
  `Total image weight: ${formatBytes(totalBytes)}`,
  `Images over 1 MB: ${largeImages.length}`,
  "",
  "## Largest Images",
  "",
  "| File | Size |",
  "| --- | ---: |",
  ...imageFiles.slice(0, 20).map((image) => `| \`${image.rel}\` | ${formatBytes(image.bytes)} |`),
  "",
  "## Optimization Policy",
  "",
  "- Keep original research/photography files in `public/assets/img/` unless the user explicitly approves destructive replacement.",
  "- Prefer adding generated thumbnails or CDN-sized URLs for page display instead of overwriting originals.",
  "- Keep Mission Log images under `public/assets/img/mission-log/`.",
  "- Mission Log images should keep `loading=\"lazy\"` and `decoding=\"async\"`.",
  "- Before replacing public or Mission Log images, run `npm run check`."
];

fs.mkdirSync(docsDir, { recursive: true });
fs.writeFileSync(outputPath, `${lines.join("\n")}\n`);

console.log(`Wrote ${path.relative(root, outputPath)} with ${imageFiles.length} images.`);
