import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.EDGE_EXECUTABLE}),base=process.env.SITE_TEST_URL||'http://127.0.0.1:52523';
try{
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/origins-study.html#stage=2&progress=.4',{waitUntil:'domcontentloaded'});
assert((await page.locator('#description').innerText()).length>80);await page.locator('#evidence').click();assert(await page.locator('#sources').isVisible());await page.keyboard.press('Escape');
await page.locator('#viewport').scrollIntoViewIfNeeded();await page.waitForFunction(()=>window.study&&document.querySelector('.origins-study').dataset.renderState==='ready',null,{timeout:90000});
assert.equal(await page.locator('#scene').evaluate(e=>getComputedStyle(e).touchAction),'pan-y');assert.equal(await page.locator('#explore').innerText(),'Explore');await page.locator('#explore').click();assert.equal(await page.locator('#scene').evaluate(e=>getComputedStyle(e).touchAction),'none');await page.locator('#explore').click();assert.equal(await page.locator('#scene').evaluate(e=>getComputedStyle(e).touchAction),'pan-y');
const order=await page.evaluate(()=>{const q=s=>document.querySelector(s).getBoundingClientRect().top;return q('.chapters')<q('.scene-frame')&&q('.scene-frame')<q('.chapter-copy');});assert(order,'chapters precede model, explanation follows on mobile');
await page.locator('#play').click();await page.waitForTimeout(180);await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.waitForFunction(()=>document.querySelector('.origins-study').dataset.inView==='false');const progress=await page.evaluate(()=>study.state.progress);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>study.state.progress),progress,'offscreen progression pauses');
await page.locator('#viewport').scrollIntoViewIfNeeded();await page.waitForTimeout(120);await page.evaluate(()=>{study.select(1,.6);study.setPhase(true);document.querySelector('#scene').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext();});await page.locator('#retry-scene').waitFor();assert(await page.locator('#evidence').isEnabled());const interruptedProgress=await page.evaluate(()=>study.state.progress);await page.locator('#retry-scene').click();await page.waitForFunction(()=>window.study&&document.querySelector('.origins-study').dataset.renderState==='ready',null,{timeout:90000});assert(await page.locator('#retry-scene').isHidden());assert.equal(await page.evaluate(()=>study.state.stage),1);assert.equal(await page.evaluate(()=>study.state.progress),interruptedProgress);assert.equal(await page.evaluate(()=>study.state.phase),true);
assert.deepEqual(errors,[]);console.log('PASS Origins readable startup, source dialog, mobile ordering, explicit touch, offscreen pause and graphics retry');
}finally{await browser.close();}
