import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({headless:true,...(process.env.EDGE_EXECUTABLE?{executablePath:process.env.EDGE_EXECUTABLE}:{})});
try {
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  await page.goto(`${process.env.SITE_TEST_URL || 'http://127.0.0.1:4322'}/research.html`,{waitUntil:'networkidle'});
  const root = page.locator('.planetary');
  await root.locator('[data-stage]').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('.planetary').dataset.renderState==='ready');
  assert.equal(await root.locator('[data-time-controls]').count(),1,'Date-driven playback controls must exist');
  await root.locator('[data-date]').fill('2026-09-07T00:00');
  await root.locator('[data-date]').dispatchEvent('change');
  const day = Number(await root.getAttribute('data-day'));
  const earthBefore = await root.locator('[data-object="earth"]').boundingBox();
  await root.locator('[data-action="play"]').click();
  await page.waitForTimeout(400);
  assert.ok(Number(await root.getAttribute('data-day'))>day+1);
  const earthAfter = await root.locator('[data-object="earth"]').boundingBox();
  assert.ok(Math.hypot(earthAfter.x-earthBefore.x,earthAfter.y-earthBefore.y)>1,'The time change must visibly move Earth');
  await root.locator('[data-action="play"]').click();
  const paused = await root.getAttribute('data-day');
  await page.waitForTimeout(250);
  assert.equal(await root.getAttribute('data-day'),paused);
  await root.locator('canvas').scrollIntoViewIfNeeded();
  const box = await root.locator('canvas').boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
  await page.mouse.wheel(0,-400);
  await page.waitForTimeout(150);
  assert.ok(Number(await root.getAttribute('data-zoom'))>1.1,'Wheel zoom must change camera magnification');
  await root.locator('[data-action="reset"]').click();
  assert.equal(Number(await root.getAttribute('data-zoom')),1);
  await root.locator('[data-action="zoom-out"]').click();
  assert.ok(Number(await root.getAttribute('data-zoom'))<1);
  await root.locator('[data-action="now"]').click();
  assert.equal(await root.locator('[data-speed]').inputValue(),'1');
  assert.match(await root.locator('[data-clock-status]').innerText(),/Current clock/);
  await root.locator('[data-date]').focus();
  assert.equal(await root.locator('[data-action="play"]').getAttribute('aria-pressed'),'false','Editing the date pauses playback so it cannot overwrite the input');
  await root.locator('[data-date]').fill('2030-12-31T23:59');
  await root.locator('[data-date]').dispatchEvent('change');
  await root.locator('[data-speed]').selectOption('31557600');
  await root.locator('[data-action="play"]').click();
  await page.waitForTimeout(200);
  assert.equal(Number(await root.getAttribute('data-day')),Number(await root.locator('[data-timeline]').getAttribute('max'))/24);
  assert.equal(await root.locator('[data-timeline]').inputValue(),await root.locator('[data-timeline]').getAttribute('max'),'Range must reach the last cached hour exactly');
  assert.equal(await root.locator('[data-action="play"]').getAttribute('aria-pressed'),'false');
  await page.evaluate(()=>{window.__dateNow=Date.now;Date.now=()=>Date.parse('2035-01-01T00:00:00Z');});
  await root.locator('[data-action="now"]').click();
  assert.match(await root.locator('[data-clock-status]').innerText(),/outside the cached/);
  assert.equal(await root.locator('[data-action="play"]').getAttribute('aria-pressed'),'false');
  await page.evaluate(()=>{Date.now=window.__dateNow;});
  await root.locator('[data-action="now"]').click();
  await root.locator('[data-view="shape"]').click();
  assert.equal(await root.locator('[data-time-controls]').isVisible(),false);
  console.log('Planetary playback: shared date, advancing/paused clock, current-time mode, wheel/button zoom and reset passed.');
} finally { await browser.close(); }
