import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.EDGE_EXECUTABLE}),base=process.env.SITE_TEST_URL||'http://127.0.0.1:52523';
try{
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>sessionStorage.setItem('mads-cosmic-arrival-v1','done'));
await page.goto(base+'/index.html',{waitUntil:'networkidle'});await page.evaluate(()=>window.sharedDocument=document);
await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').innerText(),'Skip to content');await page.keyboard.press('Enter');assert.equal(await page.locator(':focus').getAttribute('id'),'main-content');
const link=page.locator('main a[href="paper-shelf.html"]').first();await link.scrollIntoViewIfNeeded();const returnY=await page.evaluate(()=>scrollY);await link.click();await page.waitForURL('**/paper-shelf.html');await page.waitForFunction(()=>document.activeElement?.tagName==='H1');
assert(await page.evaluate(()=>window.sharedDocument===document),'body links share the document');assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'),'https://erdwmads.github.io/paper-shelf.html');
assert.equal(await page.locator('[data-paper-card] .paper-source').count(),11);await page.locator('[data-paper-search]').fill('qzxnomatch');assert.equal(await page.locator('[data-paper-card]:visible').count(),0);assert.match(await page.locator('[data-paper-count]').innerText(),/0 of 11/);assert(await page.locator('[data-paper-empty]').isVisible());await page.locator('[data-paper-reset]').click();assert.equal(await page.locator('[data-paper-card]:visible').count(),11);await page.locator('[data-paper-filter="chronology"]').click();assert.equal(await page.locator('[data-paper-card]:visible').count(),1);await page.locator('.nav a[href="paper-shelf.html"]').click();assert.equal(await page.locator('[data-paper-card]:visible').count(),1,'active navigation must preserve page state');
await page.goBack();await page.waitForURL(/\/index\.html(?:#.*)?$/);await page.waitForFunction(y=>Math.abs(scrollY-y)<5,returnY);assert(await page.evaluate(()=>window.sharedDocument===document));
await page.locator('.nav a[href="cv.html"]').click();await page.waitForURL('**/cv.html');assert.match(await page.locator('.cv-edu-card').first().innerText(),/2025/);
await page.locator('.nav a[href="contact.html"]').click();await page.waitForURL('**/contact.html');await page.waitForFunction(()=>document.activeElement?.tagName==='H1');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>window.copied=text}}));await page.locator('[data-email-copy]').click();assert.equal(await page.evaluate(()=>window.copied),'rivieraliuyong@fuji.waseda.jp');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied');}}}));await page.locator('[data-email-copy]').click();assert.match(await page.locator('[data-email-status]').innerText(),/selected/);
await page.locator('.nav a[href="photography.html"]').click();await page.waitForURL('**/photography.html');assert.equal(await page.locator('.photo-tile').count(),21);assert((await page.locator('.photo-tile img').evaluateAll(es=>es.map(e=>e.alt))).every(alt=>alt.length>25&&!/^Photograph \d+$/.test(alt)));
for(const route of ['research-log','research-graduation']){await page.goto(base+'/'+route+'.html',{waitUntil:'networkidle'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
assert.equal(await page.locator('[data-research-lock-content]').isVisible(),false);assert.equal(await page.locator('.nav-log-gate').getAttribute('aria-current'),'page');
assert.deepEqual(errors,[]);console.log('PASS full-site navigation, focus, Back position, source links, empty/reset search, recent CV, email copy/fallback, 21 photo descriptions and archive boundary');
}finally{await browser.close();}
